# Generated by Django 5.2.17 on 2026-09-30 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_remove_drivers_license_fields'),
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='začátek')),
                ('ends_at', models.DateTimeField(verbose_name='konec')),
                ('status', models.CharField(choices=[('draft', 'Návrh'), ('published', 'Publikováno'), ('cancelled', 'Zrušeno')], db_index=True, default='draft', max_length=16, verbose_name='stav')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='verze')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='employees.employee', verbose_name='zaměstnanec')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='workplaces.workplace', verbose_name='pracoviště')),
            ],
            options={
                'verbose_name': 'směna',
                'verbose_name_plural': 'směny',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['employee', 'starts_at'], name='shifts_shif_employe_f496c0_idx'), models.Index(fields=['workplace', 'starts_at'], name='shifts_shif_workpla_6975e6_idx'), models.Index(fields=['status'], name='shifts_shif_status_8c03df_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='shift_ends_after_starts')],
            },
        ),
    ]
