# Generated by Django 5.2.17 on 2026-09-30 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='symbol')),
                ('name', models.CharField(max_length=80, verbose_name='název')),
                ('start_time', models.TimeField(verbose_name='začátek')),
                ('end_time', models.TimeField(verbose_name='konec')),
                ('break_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='neplacená pauza (min)')),
                ('counts_as_work', models.BooleanField(default=True, verbose_name='započítat do plánu')),
                ('applies_on_holiday', models.BooleanField(default=True, verbose_name='povoleno ve svátek')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'typ směny',
                'verbose_name_plural': 'typy směn',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='shifts.shifttype', verbose_name='typ směny'),
        ),
    ]
