# Generated by Django 5.2.17 on 2026-09-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_drivers_license_fields'),
        ('shifts', '0003_seed_shift_types'),
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='název')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('friday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shifts.shifttype', verbose_name='pátek')),
                ('monday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shifts.shifttype', verbose_name='pondělí')),
                ('saturday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shifts.shifttype', verbose_name='sobota')),
                ('sunday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shifts.shifttype', verbose_name='neděle')),
                ('thursday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shifts.shifttype', verbose_name='čtvrtek')),
                ('tuesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shifts.shifttype', verbose_name='úterý')),
                ('wednesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shifts.shifttype', verbose_name='středa')),
            ],
            options={
                'verbose_name': 'šablona směn',
                'verbose_name_plural': 'šablony směn',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='platnost od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='platnost do')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='employees.employee', verbose_name='zaměstnanec')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='workplaces.workplace', verbose_name='pracoviště')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='shifts.scheduletemplate', verbose_name='šablona')),
            ],
            options={
                'verbose_name': 'přiřazení šablony směn',
                'verbose_name_plural': 'přiřazení šablon směn',
                'ordering': ['-valid_from', 'employee_id'],
                'indexes': [models.Index(fields=['employee', 'valid_from'], name='shifts_empl_employe_62f02a_idx'), models.Index(fields=['is_active'], name='shifts_empl_is_acti_5ca4d7_idx')],
            },
        ),
    ]
