# Generated by Django 5.2.17 on 2026-09-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_cycle_template_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='kind',
            field=models.CharField(choices=[('work', 'Práce'), ('standby', 'Pohotovost')], db_index=True, default='work', help_text='Pohotovost se nezapočítává do odpracovaných hodin (§ 140).', max_length=16, verbose_name='druh'),
        ),
    ]
