# Generated by Django 5.2.17 on 2026-10-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_work_time_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='kód')),
                ('name', models.CharField(max_length=120, verbose_name='název')),
                ('description', models.TextField(blank=True, verbose_name='popis')),
                ('requires_number', models.BooleanField(default=False, verbose_name='vyžaduje číslo')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
                ('warn_days_before', models.PositiveSmallIntegerField(default=30, help_text='Kolik dní před koncem platnosti zobrazit varování.', verbose_name='upozornit dní před expirací')),
            ],
            options={
                'verbose_name': 'typ dokladu vozidla',
                'verbose_name_plural': 'typy dokladů vozidel',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='SPZ')),
                ('name', models.CharField(blank=True, help_text='Volitelný popis (např. dodávka, značka).', max_length=120, verbose_name='označení')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_vehicles', to='employees.employee', verbose_name='odpovědná osoba')),
            ],
            options={
                'verbose_name': 'vozidlo',
                'verbose_name_plural': 'vozidla',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=80, verbose_name='číslo / evidenční znak')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='platnost od')),
                ('valid_until', models.DateField(blank=True, help_text='Prázdné = bez expirace.', null=True, verbose_name='platnost do')),
                ('issued_by', models.CharField(blank=True, max_length=160, verbose_name='vydal')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='technika.vehicle', verbose_name='vozidlo')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_documents', to='technika.vehicledocumenttype', verbose_name='typ')),
            ],
            options={
                'verbose_name': 'doklad vozidla',
                'verbose_name_plural': 'doklady vozidel',
                'ordering': ['document_type__sort_order', 'document_type__name'],
                'indexes': [models.Index(fields=['vehicle', 'document_type'], name='technika_ve_vehicle_df30ad_idx'), models.Index(fields=['valid_until'], name='technika_ve_valid_u_09075a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='vehicle_document_valid_until_after_from')],
            },
        ),
    ]
