# Generated by Django 5.2.17 on 2026-09-30 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='čas')),
                ('operation', models.CharField(max_length=64, verbose_name='operace')),
                ('object_type', models.CharField(max_length=128, verbose_name='typ objektu')),
                ('object_id', models.CharField(max_length=64, verbose_name='identifikátor objektu')),
                ('detail', models.TextField(blank=True, verbose_name='detail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='uživatel')),
            ],
            options={
                'verbose_name': 'auditní událost',
                'verbose_name_plural': 'auditní události',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='core_audite_object__bbabc4_idx')],
            },
        ),
    ]
