# Generated by Django 5.2.17 on 2026-10-01 15:48

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_work_time_preset'),
        ('technika', '0002_seed_document_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='název')),
                ('scope', models.CharField(choices=[('zamestnanec', 'Zaměstnanec'), ('vozidlo', 'Vozidlo')], db_index=True, max_length=16, verbose_name='okruh')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
            ],
            options={
                'verbose_name': 'šablona dokumentu',
                'verbose_name_plural': 'šablony dokumentů',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='číslo verze')),
                ('file', models.FileField(upload_to=apps.documents.models.template_upload_to, verbose_name='soubor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.documenttemplate', verbose_name='šablona')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='nahrál')),
            ],
            options={
                'verbose_name': 'verze šablony',
                'verbose_name_plural': 'verze šablon',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='StoredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='název')),
                ('file', models.FileField(upload_to=apps.documents.models.stored_upload_to, verbose_name='soubor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('missing_placeholders', models.TextField(blank=True, help_text='Seznam tokenů, které zůstaly prázdné při generování.', verbose_name='nevyplněné placeholdery')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stored_documents', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stored_documents', to='employees.employee', verbose_name='zaměstnanec')),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_documents', to='documents.documenttemplateversion', verbose_name='verze šablony')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stored_documents', to='technika.vehicle', verbose_name='vozidlo')),
            ],
            options={
                'verbose_name': 'uložený dokument',
                'verbose_name_plural': 'uložené dokumenty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documenttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='documents_template_version_unique'),
        ),
        migrations.AddIndex(
            model_name='storeddocument',
            index=models.Index(fields=['employee', 'is_active'], name='documents_s_employe_551275_idx'),
        ),
        migrations.AddIndex(
            model_name='storeddocument',
            index=models.Index(fields=['vehicle', 'is_active'], name='documents_s_vehicle_107843_idx'),
        ),
        migrations.AddConstraint(
            model_name='storeddocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('vehicle__isnull', True)), models.Q(('employee__isnull', True), ('vehicle__isnull', False)), _connector='OR'), name='documents_stored_exactly_one_target'),
        ),
    ]
