# Generated by Django 5.2.17 on 2026-10-01 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_work_time_preset'),
        ('shifts', '0007_shift_kind_leave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_weeks_wage', models.PositiveSmallIntegerField(default=4, help_text='Zákonné minimum pro mzdový režim (§ 212).', verbose_name='výměra týdnů (mzda)')),
                ('default_weeks_salary', models.PositiveSmallIntegerField(default=5, help_text='Výchozí pro platový režim.', verbose_name='výměra týdnů (plat)')),
                ('carryover_min_weeks_kept', models.PositiveSmallIntegerField(default=4, help_text='Část nároku, kterou nelze převést (zákonné minimum).', verbose_name='nepřevoditelné týdny')),
                ('continuous_min_days', models.PositiveSmallIntegerField(default=14, help_text='Doporučený souvislý blok (výchozí 2 týdny).', verbose_name='min. souvislý úsek (dny)')),
                ('allow_carryover', models.BooleanField(default=True, verbose_name='povolit převod do dalšího roku')),
                ('enforce_continuous_block', models.BooleanField(default=False, help_text='Při zapnutí nelze schválit rok bez alespoň jednoho dostatečně dlouhého bloku.', verbose_name='vyžadovat souvislý úsek')),
                ('prefer_older_entitlement', models.BooleanField(default=True, verbose_name='čerpat nejdřív starší nárok')),
                ('warn_unused_carryover', models.BooleanField(default=True, verbose_name='upozornit na nevyčerpaný převod')),
                ('block_overlap_with_work_shifts', models.BooleanField(default=True, verbose_name='blokovat překryv se směnou práce')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
            ],
            options={
                'verbose_name': 'pravidla dovolené',
                'verbose_name_plural': 'pravidla dovolené',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_weeks', models.PositiveSmallIntegerField(default=0, help_text='Nad rámec výchozí výměry z pravidel.', verbose_name='navíc týdnů')),
                ('enforce_continuous_block', models.BooleanField(blank=True, help_text='Prázdné = podle globálních pravidel.', null=True, verbose_name='vynutit souvislý úsek')),
                ('allow_carryover', models.BooleanField(blank=True, help_text='Prázdné = podle globálních pravidel.', null=True, verbose_name='povolit převod')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('employment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_settings', to='employees.employment', verbose_name='pracovní vztah')),
            ],
            options={
                'verbose_name': 'nastavení dovolené zaměstnance',
                'verbose_name_plural': 'nastavení dovolené zaměstnanců',
            },
        ),
        migrations.CreateModel(
            name='LeavePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='rok')),
                ('starts_on', models.DateField(verbose_name='od')),
                ('ends_on', models.DateField(verbose_name='do')),
                ('total_minutes', models.PositiveIntegerField(default=0, verbose_name='celkem minut')),
                ('status', models.CharField(choices=[('draft', 'Návrh'), ('approved', 'Schváleno'), ('cancelled', 'Zrušeno')], db_index=True, default='draft', max_length=16, verbose_name='stav')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='verze')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_plans', to=settings.AUTH_USER_MODEL, verbose_name='schválil')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_plans', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_plans', to='employees.employment', verbose_name='pracovní vztah')),
            ],
            options={
                'verbose_name': 'plán dovolené',
                'verbose_name_plural': 'plány dovolené',
                'ordering': ['-starts_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeavePlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='den')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='minuty')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='leave.leaveplan', verbose_name='plán')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_plan_days', to='shifts.shift', verbose_name='směna')),
            ],
            options={
                'verbose_name': 'den plánu dovolené',
                'verbose_name_plural': 'dny plánu dovolené',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='rok')),
                ('entitled_minutes', models.PositiveIntegerField(default=0, verbose_name='nárok (min)')),
                ('carried_in_minutes', models.PositiveIntegerField(default=0, verbose_name='převod z minulého roku')),
                ('planned_minutes', models.PositiveIntegerField(default=0, verbose_name='naplánováno (min)')),
                ('taken_minutes', models.PositiveIntegerField(default=0, verbose_name='vyčerpáno (min)')),
                ('must_use_by', models.DateField(blank=True, null=True, verbose_name='vyčerpat převod do')),
                ('source_note', models.CharField(blank=True, max_length=255, verbose_name='zdroj výpočtu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entitlements', to='employees.employment', verbose_name='pracovní vztah')),
            ],
            options={
                'verbose_name': 'nárok dovolené',
                'verbose_name_plural': 'nároky dovolené',
                'ordering': ['-year', 'employment_id'],
                'constraints': [models.UniqueConstraint(fields=('employment', 'year'), name='leave_entitlement_unique_employment_year')],
            },
        ),
        migrations.AddIndex(
            model_name='leaveplan',
            index=models.Index(fields=['employment', 'year'], name='leave_leave_employm_ec7ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveplan',
            index=models.Index(fields=['status'], name='leave_leave_status_d61078_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaveplanday',
            constraint=models.UniqueConstraint(fields=('plan', 'day'), name='leave_plan_day_unique'),
        ),
    ]
