# Generated by Django 5.2.17 on 2026-10-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavesettings',
            name='allow_half_day',
            field=models.BooleanField(blank=True, help_text='Prázdné = podle globálních pravidel.', null=True, verbose_name='povolit půldenní dovolenou'),
        ),
        migrations.AddField(
            model_name='leaveplan',
            name='portion',
            field=models.CharField(choices=[('full', 'Celý den'), ('am', 'Dopoledne'), ('pm', 'Odpoledne')], default='full', help_text='Půlden jen u jednodenního bloku.', max_length=8, verbose_name='část dne'),
        ),
        migrations.AddField(
            model_name='leaveplanday',
            name='portion',
            field=models.CharField(choices=[('full', 'Celý den'), ('am', 'Dopoledne'), ('pm', 'Odpoledne')], default='full', max_length=8, verbose_name='část dne'),
        ),
        migrations.AddField(
            model_name='leavepolicysettings',
            name='allow_half_day',
            field=models.BooleanField(default=True, help_text='Minimálně ½ směny (§ 218 odst. 6). Lze vypnout globálně.', verbose_name='povolit půldenní dovolenou'),
        ),
    ]
