# Generated by Django 5.2.17 on 2026-10-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_half_day_and_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveentitlement',
            name='accrued_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Skutečnost dle odpracovaných násobků týdenní doby (§ 213).', verbose_name='nárok naběhlý (min)'),
        ),
        migrations.AddField(
            model_name='leavepolicysettings',
            name='continuous_count_holidays',
            field=models.BooleanField(default=False, help_text='Pokud vypnuto, svátek v Po–Pá se do délky úseku nepočítá.', verbose_name='započítat svátky do souvislého úseku'),
        ),
        migrations.AlterField(
            model_name='leaveentitlement',
            name='entitled_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Odhad do konce roku (pro plánování).', verbose_name='nárok odhad (min)'),
        ),
        migrations.AlterField(
            model_name='leavepolicysettings',
            name='continuous_min_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Počet pracovních dnů Po–Pá (výchozí 14). So/Ne se nepočítají.', verbose_name='min. souvislý úsek (pracovní dny)'),
        ),
        migrations.AlterField(
            model_name='leavepolicysettings',
            name='enforce_continuous_block',
            field=models.BooleanField(default=False, help_text='Při zapnutí nelze schválit blok kratší než min. souvislý úsek.', verbose_name='vyžadovat souvislý úsek'),
        ),
    ]
