# Generated by Django 5.2.17 on 2026-10-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_fix_must_use_by_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveentitlement',
            name='must_use_by',
            field=models.DateField(blank=True, help_text='Jen při převodu z minulého roku (§ 218 odst. 3). Lhůty vlastního nároku roku jsou počítané (ideálně / nejzazší).', null=True, verbose_name='vyčerpat převod do'),
        ),
    ]
