# Generated by Django 5.2.17 on 2026-09-30 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_work_time_preset'),
        ('shifts', '0006_shift_kind_and_qual_warn'),
        ('workplaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='kód')),
                ('name', models.CharField(max_length=80, verbose_name='název')),
                ('accounting_kind', models.CharField(choices=[('paid_leave', 'Placená nepřítomnost'), ('sick', 'Nemoc'), ('other', 'Ostatní')], default='paid_leave', max_length=16, verbose_name='druh započtení')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'typ absence',
                'verbose_name_plural': 'typy absencí',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='den')),
                ('planned_missed_minutes', models.PositiveIntegerField(help_text='Odvozeno z publikované směny, ne plošných 8 h.', verbose_name='zameškané plánované minuty')),
                ('status', models.CharField(choices=[('draft', 'Návrh'), ('approved', 'Schváleno')], db_index=True, default='approved', max_length=16, verbose_name='stav')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_absences', to=settings.AUTH_USER_MODEL, verbose_name='zapsal')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employees.employment', verbose_name='pracovní vztah')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='shifts.shift', verbose_name='směna')),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='attendance.absencetype', verbose_name='typ absence')),
            ],
            options={
                'verbose_name': 'absence',
                'verbose_name_plural': 'absence',
                'ordering': ['-day', '-id'],
                'indexes': [models.Index(fields=['employment', 'day'], name='attendance__employm_afaffb_idx'), models.Index(fields=['shift'], name='attendance__shift_i_66bae3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('shift__isnull', False)), fields=('shift',), name='absence_unique_shift')],
            },
        ),
        migrations.CreateModel(
            name='WorkInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='začátek')),
                ('ends_at', models.DateTimeField(verbose_name='konec')),
                ('break_minutes', models.PositiveSmallIntegerField(default=0, help_text='Potvrzená pauza; bez fiktivní automatické srážky.', verbose_name='neplacená pauza (min)')),
                ('status', models.CharField(choices=[('draft', 'Návrh'), ('confirmed', 'Potvrzeno')], db_index=True, default='draft', max_length=16, verbose_name='stav')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='verze')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='potvrzeno')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_work_intervals', to=settings.AUTH_USER_MODEL, verbose_name='potvrdil')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_intervals', to='employees.employment', verbose_name='pracovní vztah')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_intervals', to='shifts.shift', verbose_name='směna')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_intervals', to='workplaces.workplace', verbose_name='pracoviště')),
            ],
            options={
                'verbose_name': 'pracovní interval',
                'verbose_name_plural': 'pracovní intervaly',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['employment', 'starts_at'], name='attendance__employm_d167ab_idx'), models.Index(fields=['shift', 'status'], name='attendance__shift_i_884a1a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='work_interval_ends_after_starts')],
            },
        ),
    ]
