# Generated by Django 5.2.17 on 2026-09-30 17:23

from django.db import migrations


ABSENCE_TYPES = (
    ("dovolena", "Dovolená", "paid_leave", 10),
    ("lekar", "Lékař", "paid_leave", 20),
    ("nemoc", "Nemoc", "sick", 30),
)


def seed_types(apps, schema_editor):
    AbsenceType = apps.get_model("attendance", "AbsenceType")
    for code, name, kind, order in ABSENCE_TYPES:
        AbsenceType.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "accounting_kind": kind,
                "is_active": True,
                "sort_order": order,
            },
        )


def unseed_types(apps, schema_editor):
    AbsenceType = apps.get_model("attendance", "AbsenceType")
    AbsenceType.objects.filter(code__in=[row[0] for row in ABSENCE_TYPES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_types, unseed_types),
    ]
