# Generated by Django 5.2.17 on 2026-09-30 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='příjmení')),
                ('internal_number', models.CharField(max_length=32, unique=True, verbose_name='interní číslo')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='funkce')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('work_contact', models.CharField(blank=True, help_text='Volitelné, jen podle potřeby.', max_length=200, verbose_name='pracovní kontakt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='účet')),
            ],
            options={
                'verbose_name': 'zaměstnanec',
                'verbose_name_plural': 'zaměstnanci',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
