# Generated by Django 5.2.17 on 2026-09-30 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='drivers_license_categories',
            field=models.CharField(blank=True, help_text='Např. B, C.', max_length=60, verbose_name='skupiny řidičského průkazu'),
        ),
        migrations.AddField(
            model_name='employee',
            name='drivers_license_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='číslo řidičského průkazu'),
        ),
        migrations.AddField(
            model_name='employee',
            name='drivers_license_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='platnost řidičského průkazu'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='poznámka'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='telefon'),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('PP', 'Pracovní poměr'), ('DPP', 'Dohoda o provedení práce'), ('DPČ', 'Dohoda o pracovní činnosti')], default='PP', max_length=8, verbose_name='druh vztahu')),
                ('started_on', models.DateField(verbose_name='den nástupu')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='den ukončení')),
                ('payroll_number', models.CharField(blank=True, help_text='Ukládejte jako text včetně počátečních nul.', max_length=32, verbose_name='mzdové číslo')),
                ('pay_regime', models.CharField(choices=[('mzda', 'Mzda'), ('plat', 'Plat')], default='mzda', max_length=8, verbose_name='režim odměňování')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='funkce ve vztahu')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní vztah')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='employees.employee', verbose_name='zaměstnanec')),
            ],
            options={
                'verbose_name': 'pracovní vztah',
                'verbose_name_plural': 'pracovní vztahy',
                'ordering': ['-started_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='employment_ended_on_after_started_on')],
            },
        ),
    ]
