# Generated by Django 5.2.17 on 2026-09-30 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_employment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='kód')),
                ('name', models.CharField(max_length=120, verbose_name='název')),
                ('description', models.TextField(blank=True, verbose_name='popis')),
                ('requires_number', models.BooleanField(default=False, verbose_name='vyžaduje číslo')),
                ('requires_categories', models.BooleanField(default=False, help_text='Např. skupiny řidičského průkazu B, C.', verbose_name='vyžaduje skupiny/kategorie')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'typ kvalifikace',
                'verbose_name_plural': 'typy kvalifikací',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=80, verbose_name='číslo / evidenční znak')),
                ('categories', models.CharField(blank=True, help_text='Např. B, C nebo § 6.', max_length=80, verbose_name='skupiny / rozsah')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='platnost od')),
                ('valid_until', models.DateField(blank=True, help_text='Prázdné = bez expirace.', null=True, verbose_name='platnost do')),
                ('issued_by', models.CharField(blank=True, max_length=160, verbose_name='vydal')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='employees.employee', verbose_name='zaměstnanec')),
                ('qualification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_qualifications', to='employees.qualificationtype', verbose_name='typ')),
            ],
            options={
                'verbose_name': 'kvalifikace zaměstnance',
                'verbose_name_plural': 'kvalifikace zaměstnanců',
                'ordering': ['qualification_type__sort_order', 'qualification_type__name'],
                'indexes': [models.Index(fields=['employee', 'qualification_type'], name='employees_e_employe_4cf102_idx'), models.Index(fields=['valid_until'], name='employees_e_valid_u_1efbc9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='qualification_valid_until_after_from')],
            },
        ),
    ]
