# Generated by Django 5.2.17 on 2026-09-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_seed_qualifications_migrate_licenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='drivers_license_categories',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='drivers_license_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='drivers_license_valid_until',
        ),
    ]
