# Generated by Django 5.2.17 on 2026-09-30 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_drivers_license_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='platnost od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='platnost do')),
                ('statutory_weekly_minutes', models.PositiveIntegerField(default=2400, help_text='Např. 40 h = 2400, 37,5 h = 2250.', verbose_name='stanovená týdenní doba (min)')),
                ('agreed_weekly_minutes', models.PositiveIntegerField(default=2400, verbose_name='sjednaná týdenní doba (min)')),
                ('regime', models.CharField(choices=[('single', 'Jednosměnný'), ('two', 'Dvousměnný'), ('multi', 'Vícesměnný'), ('continuous', 'Nepřetržitý')], default='single', max_length=16, verbose_name='režim')),
                ('distribution', models.CharField(choices=[('even', 'Rovnoměrné'), ('uneven', 'Nerovnoměrné')], default='even', max_length=16, verbose_name='rozvržení')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_time_profiles', to='employees.employment', verbose_name='pracovní vztah')),
            ],
            options={
                'verbose_name': 'profil pracovní doby',
                'verbose_name_plural': 'profily pracovní doby',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='BalancingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(verbose_name='začátek')),
                ('ends_on', models.DateField(verbose_name='konec')),
                ('kind', models.CharField(choices=[('schedule', 'Vyrovnání rozvrhu'), ('overtime', 'Vyrovnání přesčasů')], default='schedule', max_length=16, verbose_name='druh')),
                ('target_minutes', models.PositiveIntegerField(help_text='Cílové minuty za období. Lze nechat dopočítat ze sjednané týdenní doby.', verbose_name='cílový fond (min)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancing_periods', to='employees.worktimeprofile', verbose_name='profil')),
            ],
            options={
                'verbose_name': 'vyrovnávací období',
                'verbose_name_plural': 'vyrovnávací období',
                'ordering': ['-starts_on'],
            },
        ),
    ]
