# Generated by Django 5.2.17 on 2026-09-30 14:17

from django.db import migrations, models


def set_default_warn_days(apps, schema_editor):
    QualificationType = apps.get_model("employees", "QualificationType")
    QualificationType.objects.filter(code="ridicsky_prukaz").update(warn_days_before=30)
    QualificationType.objects.filter(code="elektro").update(warn_days_before=60)


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_work_time_balancing"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualificationtype",
            name="warn_days_before",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Kolik dní před koncem platnosti zobrazit varování.",
                verbose_name="upozornit dní před expirací",
            ),
        ),
        migrations.RunPython(set_default_warn_days, migrations.RunPython.noop),
    ]
