# Generated by Django 5.2.17 on 2026-09-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='název')),
                ('workplace_type', models.CharField(choices=[('parking_house', 'Parkovací dům'), ('office', 'Kancelář'), ('other', 'Jiné')], default='parking_house', max_length=32, verbose_name='typ')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresa')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
            ],
            options={
                'verbose_name': 'pracoviště',
                'verbose_name_plural': 'pracoviště',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='platnost od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='platnost do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workplace_assignments', to='employees.employee', verbose_name='zaměstnanec')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='workplaces.workplace', verbose_name='pracoviště')),
            ],
            options={
                'verbose_name': 'přiřazení k pracovišti',
                'verbose_name_plural': 'přiřazení k pracovištím',
                'ordering': ['-valid_from', 'employee_id'],
                'indexes': [models.Index(fields=['employee', 'workplace'], name='workplaces__employe_21baa6_idx'), models.Index(fields=['valid_from', 'valid_to'], name='workplaces__valid_f_a82475_idx')],
            },
        ),
    ]
