# Generated by Django 5.2.17 on 2026-09-30 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_work_time_preset'),
        ('shifts', '0006_shift_kind_and_qual_warn'),
        ('workplaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='kód')),
                ('name', models.CharField(max_length=80, verbose_name='název')),
                ('travel_mode', models.CharField(choices=[('none', 'Bez přesunu'), ('car', 'Automobilem'), ('walk', 'Pěšky')], default='none', help_text='Pro budoucí výpočet přejezdů; v této etapě jen evidence.', max_length=16, verbose_name='způsob přesunu')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'typ činnosti',
                'verbose_name_plural': 'typy činností',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='kód')),
                ('name', models.CharField(max_length=120, verbose_name='název')),
                ('description', models.TextField(blank=True, verbose_name='popis')),
                ('geojson', models.TextField(help_text='Polygon lokality (GeoJSON Feature nebo Geometry).', verbose_name='GeoJSON polygon')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktivní')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_locations', to='workplaces.workplace', verbose_name='pracoviště')),
            ],
            options={
                'verbose_name': 'lokalita činnosti',
                'verbose_name_plural': 'lokality činností',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='den')),
                ('starts_at', models.DateTimeField(verbose_name='začátek')),
                ('ends_at', models.DateTimeField(verbose_name='konec')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='poznámka')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='verze')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activity_items', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_items', to='employees.employee', verbose_name='zaměstnanec')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_items', to='shifts.shift', verbose_name='směna')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_items', to='activities.activitylocation', verbose_name='lokalita')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_items', to='activities.activitytype', verbose_name='typ činnosti')),
            ],
            options={
                'verbose_name': 'činnost',
                'verbose_name_plural': 'činnosti',
                'ordering': ['day', 'sort_order', 'starts_at', 'id'],
                'indexes': [models.Index(fields=['employee', 'day'], name='activities__employe_691e30_idx'), models.Index(fields=['shift'], name='activities__shift_i_89c0d6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='activity_item_ends_after_starts')],
            },
        ),
    ]
