# Generated by Django 5.2.17 on 2026-09-30 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_seed_activity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylocation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Prázdné = hlavní lokace. Jinak podlokace (max. jedna úroveň).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='activities.activitylocation', verbose_name='nadřazená lokace'),
        ),
    ]
