# Generated by Django 5.2.17 on 2026-09-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_mapcity_and_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcity',
            name='center_lat',
            field=models.DecimalField(decimal_places=6, help_text='Pořadí: lat, lon (např. Mladá Boleslav ≈ 50.411350, 14.903180).', max_digits=9, verbose_name='zeměpisná šířka (lat)'),
        ),
        migrations.AlterField(
            model_name='mapcity',
            name='center_lon',
            field=models.DecimalField(decimal_places=6, help_text='Nepřehazujte lat a lon.', max_digits=9, verbose_name='zeměpisná délka (lon)'),
        ),
    ]
