# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_activitylocation_color"),
        ("employees", "0008_work_time_preset"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Relativní podíl hodin ve směně (např. 2 a 1 = 2/3 a 1/3).",
                        verbose_name="četnost (váha)",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="pořadí"
                    ),
                ),
                (
                    "default_activity_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pro generátor a budoucí požadavky; prázdné = výchozí typ z číselníku.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_preferences",
                        to="activities.activitytype",
                        verbose_name="výchozí typ činnosti",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_preferences",
                        to="employees.employee",
                        verbose_name="zaměstnanec",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_preferences",
                        to="activities.activitylocation",
                        verbose_name="lokalita",
                    ),
                ),
            ],
            options={
                "verbose_name": "preference činnosti",
                "verbose_name_plural": "preference činností",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="activitypreference",
            constraint=models.UniqueConstraint(
                fields=("employee", "location"),
                name="activity_pref_employee_location_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitypreference",
            constraint=models.CheckConstraint(
                condition=models.Q(("frequency__gte", 1)),
                name="activity_pref_frequency_gte_1",
            ),
        ),
    ]
