# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0008_activitypreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityitem",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Volitelné — činnost může být i bez lokality (požadavek, poznámka).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_items",
                to="activities.activitylocation",
                verbose_name="lokalita",
            ),
        ),
    ]
