# Generated by Django 5.2.17 on 2026-10-01 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_export_activity_plan_perm'),
        ('technika', '0001_initial_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityitem',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Volitelné — jen pokud je vozidlo potřeba.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_items', to='technika.vehicle', verbose_name='vozidlo'),
        ),
        migrations.AlterField(
            model_name='activitylocation',
            name='color',
            field=models.CharField(default='#166999', help_text='Barva polygonu na mapě (#RRGGBB).', max_length=7, validators=[django.core.validators.RegexValidator(message='Zadejte barvu ve formátu #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='barva'),
        ),
    ]
